<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<title>Weekly Wage Sheet</title>

<style>

body{
    font-family: DejaVu Sans, sans-serif;
    font-size:11px;
    color:#222;
}

table{
    width:100%;
    border-collapse:collapse;
}

th,td{
    border:1px solid #999;
    padding:4px;
    vertical-align:middle;
}

th{
    background:#eaf2ff;
    font-weight:bold;
    text-align:center;
}

.heading{
    font-size:20px;
    font-weight:bold;
    text-align:center;
    margin-bottom:2px;
}

.subheading{
    text-align:center;
    margin-bottom:15px;
    color:#666;
}

.section{
    margin-top:15px;
    margin-bottom:8px;
    font-size:14px;
    font-weight:bold;
}

.text-right{
    text-align:right;
}

.text-center{
    text-align:center;
}

.small{
    font-size:10px;
    color:#666;
}

.summary td{
    font-weight:bold;
    background:#f6f6f6;
}

.group-heading td{background:#eff6ff;color:#1e3a8a;font-weight:bold;}
.group-subtotal td{background:#f8fafc;font-weight:bold;border-top:1.5px solid #93c5fd;}

.meta td{
    border:none;
    padding:3px 0;
}

</style>

</head>

<body>

<div class="heading">
Ravion ERP - Weekly Wage Sheet
</div>

<div class="subheading">

{{ $weeklyWageSheet->project->project_name }}

<br>

{{ $weeklyWageSheet->week_start_date->format('d M Y') }}

-

{{ $weeklyWageSheet->week_end_date->format('d M Y') }}

</div>


<table class="meta">

<tr>
<td width="18%"><strong>Wage Sheet</strong></td>
<td>{{ $weeklyWageSheet->wage_sheet_number }}</td>

<td width="18%"><strong>Status</strong></td>
<td>{{ ucfirst($weeklyWageSheet->status) }}</td>
</tr>

<tr>
<td><strong>Generated</strong></td>
<td>{{ optional($weeklyWageSheet->generated_at)->format('d-m-Y H:i') }}</td>

<td><strong>Generated By</strong></td>
<td>{{ optional($weeklyWageSheet->generatedBy)->name }}</td>
</tr>

</table>


<div class="section">
Labour Wage Calculations
</div>

<table>

<thead>

<tr>

<th width="4%">#</th>

<th width="20%">Labour</th>

<th width="8%">Daily Rate</th>

<th width="8%">Payable Days</th>

<th width="10%">Normal Wage</th>

<th width="8%">OT Hours</th>

<th width="8%">OT Rate</th>

<th width="10%">OT Wage</th>

<th width="8%">Additions</th>

<th width="8%">Deductions</th>

<th width="10%">Net Payable</th>

</tr>

</thead>

<tbody>

@php
$groupedDetails = $weeklyWageSheet->details
    ->sortBy(fn ($detail) => sprintf('%08d|%s|%s', (int) ($detail->labour?->labourGroup?->sort_order ?? 999999), strtolower((string) ($detail->labour?->labourGroup?->name ?? 'Un-grouped Labour')), strtolower((string) ($detail->labour?->full_name ?? ''))))
    ->groupBy(fn ($detail) => $detail->labour?->labourGroup?->name ?? 'Un-grouped Labour');
$serial = 1;
@endphp

@foreach($groupedDetails as $groupName => $groupDetails)
<tr class="group-heading"><td colspan="11">Labour Group: {{ $groupName }} ({{ $groupDetails->count() }} Labour)</td></tr>
@foreach($groupDetails as $detail)

<tr>

<td class="text-center">
{{ $serial++ }}
</td>

<td>

<strong>

{{ optional($detail->labour)->full_name }}

</strong>

<br>

<span class="small">

{{ optional($detail->designationRole)->name }}

</span>

</td>

<td class="text-right">
{{ number_format($detail->daily_wage_rate,2) }}
</td>

<td class="text-center">
{{ number_format($detail->payable_days,2) }}
</td>

<td class="text-right">
{{ number_format($detail->normal_wage,2) }}
</td>

<td class="text-center">
{{ number_format($detail->ot_hours,2) }}
</td>

<td class="text-right">
{{ number_format($detail->ot_hourly_rate,2) }}
</td>

<td class="text-right">
{{ number_format($detail->ot_wage,2) }}
</td>

<td class="text-right">
{{ number_format($detail->additions,2) }}
</td>

<td class="text-right">
{{ number_format($detail->deductions,2) }}
</td>

<td class="text-right">
{{ number_format($detail->net_payable,2) }}
</td>

</tr>


@endforeach
<tr class="group-subtotal">
<td colspan="10">{{ $groupName }} - Group Wage Total</td>
<td class="text-right">{{ number_format($groupDetails->sum('net_payable'), 2) }}</td>
</tr>
@endforeach

<tr class="summary">

<td colspan="3">
Labour Totals
</td>

<td class="text-center">
{{ number_format($weeklyWageSheet->total_payable_days,2) }}
</td>

<td class="text-right">
{{ number_format($weeklyWageSheet->total_normal_wages,2) }}
</td>

<td class="text-center">
{{ number_format($weeklyWageSheet->total_ot_hours,2) }}
</td>

<td></td>

<td class="text-right">
{{ number_format($weeklyWageSheet->total_ot_wages,2) }}
</td>

<td class="text-right">
{{ number_format($weeklyWageSheet->total_labour_additions,2) }}
</td>

<td class="text-right">
{{ number_format($weeklyWageSheet->total_labour_deductions,2) }}
</td>

<td class="text-right">
{{ number_format($weeklyWageSheet->net_labour_wages,2) }}
</td>

</tr>

</tbody>

</table>


@if($weeklyWageSheet->charges->count())

<div class="section">

Site Additional Charges

</div>

<table>

<thead>

<tr>

<th>#</th>

<th>Charge Type</th>

<th>Description</th>

<th>Activity</th>

<th>Contractor</th>

<th>Amount</th>

<th>Remarks</th>

</tr>

</thead>

<tbody>

@foreach($weeklyWageSheet->charges as $charge)

<tr>

<td class="text-center">
{{ $loop->iteration }}
</td>

<td>
{{ $charge->charge_type }}
</td>

<td>
{{ $charge->description }}
</td>

<td>
{{ optional($charge->activity)->activity_name }}
</td>

<td>
{{ optional($charge->contractor)->contractor_name }}
</td>

<td class="text-right">
{{ number_format($charge->amount,2) }}
</td>

<td>
{{ $charge->remarks }}
</td>

</tr>

@endforeach

<tr class="summary">

<td colspan="5">
Site Charges Total
</td>

<td class="text-right">
{{ number_format($weeklyWageSheet->total_site_charges,2) }}
</td>

<td></td>

</tr>

</tbody>

</table>

@endif


<br>

<table>

<tr class="summary">

<td width="70%">
TOTAL PROJECT PAYABLE
</td>

<td class="text-right">

₹ {{ number_format($weeklyWageSheet->total_project_payable,2) }}

</td>

</tr>

</table>

</body>
</html>