@extends('layouts.app')
@section('content')
@php $canManage=auth()->user()?->hasPermission('location_masters.manage')??false; @endphp
<div class="max-w-[1600px] mx-auto p-6">
 <div class="flex justify-between items-end mb-5"><div><div class="text-xs font-bold uppercase tracking-widest text-blue-600">Project Setup</div><h1 class="text-2xl font-bold">Project Structure Masters</h1><p class="text-sm text-slate-500">Add, edit, activate/deactivate and control all dropdown values used by Project Structure.</p></div><a href="{{ route('project-locations.index') }}" class="border rounded-lg px-4 py-2 text-sm font-semibold">Project Structure</a></div>
 @if(session('success'))<div class="mb-4 rounded-lg bg-emerald-50 border border-emerald-200 p-3 text-sm text-emerald-800">{{session('success')}}</div>@endif
 @if($errors->any())<div class="mb-4 rounded-lg bg-red-50 border border-red-200 p-3 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
 <div class="grid xl:grid-cols-[260px_1fr] gap-5">
  <aside class="bg-white border rounded-xl p-3 h-fit"><div class="px-2 pb-2 text-xs font-bold uppercase text-slate-400">Masters</div>@foreach($masters as $key=>$m)<a href="{{route('project-structure-masters.index',['master'=>$key])}}" class="block px-3 py-2 rounded-lg text-sm {{$k===$key?'bg-blue-50 text-blue-700 font-semibold':'hover:bg-slate-50'}}">{{$m[0]}}</a>@endforeach</aside>
  <main class="bg-white border rounded-xl overflow-hidden">
   <div class="p-5 border-b flex justify-between"><div><h2 class="text-lg font-bold">{{$c[0]}}</h2><p class="text-sm text-slate-500">Controlled master values. Deactivate obsolete values instead of deleting them.</p></div><div class="text-sm text-slate-500">{{number_format($items->total())}} records</div></div>
   <form method="GET" class="p-4 bg-slate-50 border-b grid md:grid-cols-4 gap-3"><input type="hidden" name="master" value="{{$k}}"><input name="q" value="{{request('q')}}" placeholder="Search name or code" class="rounded-lg border-slate-300 text-sm">@if($c[2])<select name="parent_id" class="rounded-lg border-slate-300 text-sm"><option value="">All {{$c[2][2]}}</option>@foreach($parents as $p)<option value="{{$p->id}}" @selected(request('parent_id')==$p->id)>{{$p->name}}</option>@endforeach</select>@else<div></div>@endif<select name="status" class="rounded-lg border-slate-300 text-sm"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><div class="flex gap-2"><button class="bg-slate-900 text-white rounded-lg px-4 py-2 text-sm font-semibold">Filter</button><a href="{{route('project-structure-masters.index',['master'=>$k])}}" class="border bg-white rounded-lg px-4 py-2 text-sm font-semibold">Reset</a></div></form>
   @if($canManage)<form method="POST" action="{{route('project-structure-masters.store',$k)}}" class="p-4 border-b grid lg:grid-cols-12 gap-3">@csrf
    @if($c[2])<div class="lg:col-span-3"><label class="text-xs font-semibold">{{$c[2][2]}}</label><select name="{{$c[2][0]}}" class="w-full rounded-lg border-slate-300 text-sm" {{empty($c[2][3])?'required':''}}><option value="">Select</option>@foreach($parents as $p)<option value="{{$p->id}}">{{$p->name}}</option>@endforeach</select></div>@endif
    <div class="lg:col-span-2"><label class="text-xs font-semibold">Code</label><input name="code" required placeholder="MASTER_CODE" class="w-full rounded-lg border-slate-300 text-sm"></div><div class="lg:col-span-3"><label class="text-xs font-semibold">Name</label><input name="name" required class="w-full rounded-lg border-slate-300 text-sm"></div>
    @if($k==='level-types')<div class="lg:col-span-2"><label class="text-xs font-semibold">Name Pattern</label><input name="name_pattern" placeholder="Cellar {n}" class="w-full rounded-lg border-slate-300 text-sm"></div><div class="lg:col-span-2"><label class="text-xs font-semibold">Number Mode</label><select name="number_mode" class="w-full rounded-lg border-slate-300 text-sm"><option value="integer">Integer</option><option value="custom">Custom</option></select><label class="text-xs"><input type="checkbox" name="requires_number" value="1"> Requires number</label></div>@else<div class="lg:col-span-2"><label class="text-xs font-semibold">Aliases</label><input name="aliases_text" placeholder="Comma separated" class="w-full rounded-lg border-slate-300 text-sm"></div>@endif
    <div class="lg:col-span-1"><label class="text-xs font-semibold">Sort</label><input name="sort_order" type="number" min="0" value="0" class="w-full rounded-lg border-slate-300 text-sm"></div><div class="lg:col-span-1 flex items-end"><button class="w-full bg-blue-600 text-white rounded-lg px-3 py-2 text-sm font-semibold">Add</button></div><div class="lg:col-span-12"><input name="description" placeholder="Description / remarks (optional)" class="w-full rounded-lg border-slate-300 text-sm"></div>
   </form>@endif
   <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3 text-left">Code</th><th class="p-3 text-left">Name</th>@if($c[2])<th class="p-3 text-left">{{$c[2][2]}}</th>@endif @if($k==='level-types')<th class="p-3 text-left">Pattern</th>@endif<th class="p-3">Sort</th><th class="p-3">Status</th>@if($canManage)<th class="p-3 text-right">Actions</th>@endif</tr></thead><tbody class="divide-y">@forelse($items as $x)<tr><td class="p-3 font-mono text-xs">{{$x->code}}</td><td class="p-3"><b>{{$x->name}}</b>@if($x->description)<div class="text-xs text-slate-500">{{$x->description}}</div>@endif</td>@if($c[2])<td class="p-3">{{optional($parents->firstWhere('id',$x->{$c[2][0]}))->name ?? '—'}}</td>@endif @if($k==='level-types')<td class="p-3">{{$x->name_pattern??'—'}}</td>@endif<td class="p-3 text-center">{{$x->sort_order}}</td><td class="p-3 text-center"><span class="rounded-full px-2 py-1 text-xs font-semibold {{$x->is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}}">{{$x->is_active?'Active':'Inactive'}}</span></td>@if($canManage)<td class="p-3"><div class="flex justify-end gap-2"><button type="button" onclick='editMaster(@json($x))' class="border rounded-lg px-3 py-1.5 text-xs font-semibold">Edit</button><form method="POST" action="{{route('project-structure-masters.toggle',[$k,$x->id])}}">@csrf @method('PATCH')<button class="border rounded-lg px-3 py-1.5 text-xs font-semibold">{{$x->is_active?'Deactivate':'Activate'}}</button></form></div></td>@endif</tr>@empty<tr><td colspan="8" class="p-10 text-center text-slate-500">No records found.</td></tr>@endforelse</tbody></table></div><div class="p-4 border-t">{{$items->links()}}</div>
  </main>
 </div>
</div>
@if($canManage)<div id="editModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/40 p-4"><div class="bg-white rounded-xl w-full max-w-2xl shadow-2xl"><div class="p-4 border-b flex justify-between"><b>Edit {{$c[0]}}</b><button type="button" onclick="closeEdit()">✕</button></div><form id="editForm" method="POST" class="p-5 grid md:grid-cols-2 gap-3">@csrf @method('PUT')@if($c[2])<div class="md:col-span-2"><label class="text-xs font-semibold">{{$c[2][2]}}</label><select id="ep" name="{{$c[2][0]}}" class="w-full rounded-lg border-slate-300 text-sm"><option value="">Select</option>@foreach($parents as $p)<option value="{{$p->id}}">{{$p->name}}</option>@endforeach</select></div>@endif<div><label class="text-xs font-semibold">Code</label><input id="ec" name="code" required class="w-full rounded-lg border-slate-300"></div><div><label class="text-xs font-semibold">Name</label><input id="en" name="name" required class="w-full rounded-lg border-slate-300"></div>@if($k==='level-types')<div><label class="text-xs font-semibold">Name Pattern</label><input id="ept" name="name_pattern" class="w-full rounded-lg border-slate-300"></div><div><select id="enm" name="number_mode" class="w-full rounded-lg border-slate-300"><option value="integer">Integer</option><option value="custom">Custom</option></select><label class="text-xs"><input id="ern" type="checkbox" name="requires_number" value="1"> Requires number</label></div>@else<div class="md:col-span-2"><label class="text-xs font-semibold">Aliases</label><input id="ea" name="aliases_text" class="w-full rounded-lg border-slate-300"></div>@endif<div><label class="text-xs font-semibold">Sort</label><input id="es" name="sort_order" type="number" min="0" class="w-full rounded-lg border-slate-300"></div><div class="md:col-span-2"><textarea id="ed" name="description" rows="3" class="w-full rounded-lg border-slate-300" placeholder="Description / remarks"></textarea></div><div class="md:col-span-2 flex justify-end gap-2"><button type="button" onclick="closeEdit()" class="border rounded-lg px-4 py-2">Cancel</button><button class="bg-blue-600 text-white rounded-lg px-4 py-2">Save Changes</button></div></form></div></div><script>function editMaster(x){let f=document.getElementById('editForm');f.action=@json(url('/project-structure-masters'))+'/'+@json($k)+'/'+x.id;ec.value=x.code||'';en.value=x.name||'';ed.value=x.description||'';es.value=x.sort_order||0;if(typeof ea!=='undefined')ea.value=Array.isArray(x.aliases)?x.aliases.join(', '):(x.aliases||'');if(typeof ep!=='undefined')ep.value=x[@json($c[2][0]??'')]||'';if(typeof ept!=='undefined')ept.value=x.name_pattern||'';if(typeof enm!=='undefined')enm.value=x.number_mode||'integer';if(typeof ern!=='undefined')ern.checked=!!x.requires_number;editModal.classList.remove('hidden');editModal.classList.add('flex')}function closeEdit(){editModal.classList.add('hidden');editModal.classList.remove('flex')}</script>@endif
@endsection
