@extends('layouts.app')
@section('content')
<div class="max-w-5xl mx-auto px-4 py-6 space-y-5">
 <div class="flex justify-between items-center"><div><p class="text-xs text-slate-500">Project Structure / Intelligent Room Setup</p><h1 class="text-2xl font-bold">{{ $projectRoom->name }}</h1><p class="text-sm text-slate-500">{{ $projectRoom->floor?->block?->name }} / {{ $projectRoom->floor?->name }} / {{ $projectRoom->unit?->name ?? 'Floor common space' }}</p></div><a href="{{ route('project-locations.rooms.designer',$projectRoom) }}" class="border rounded-lg px-4 py-2 text-sm">Advanced Room Designer →</a></div>
 @if($errors->any())<div class="bg-red-50 border border-red-200 text-red-800 p-3 rounded-lg">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
 <div class="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-900">Existing geometry, walls and openings will not be overwritten. Select each proposed opening's actual wall on the next screen. Attached rooms are created only when explicitly enabled and named.</div>
 <form action="{{ route('project-locations.rooms.quick-setup.preview',$projectRoom) }}" method="POST" class="bg-white border rounded-xl p-5 space-y-5">@csrf
 <h2 class="font-bold">1. Main room dimensions</h2>
 <div class="grid md:grid-cols-4 gap-3"><label class="text-sm">Unit<select name="dimension_unit" class="block w-full rounded-lg border-slate-300"><option value="ft" @selected(old('dimension_unit',$projectRoom->geometry?->dimension_unit ?? 'ft')==='ft')>Feet</option><option value="m" @selected(old('dimension_unit',$projectRoom->geometry?->dimension_unit ?? 'ft')==='m')>Metres</option></select></label>
 @foreach(['length'=>'Length','width'=>'Width','clear_height'=>'Clear height'] as $key=>$label)<label class="text-sm">{{ $label }}<input name="{{ $key }}" type="number" step="0.001" min="0.001" required value="{{ old($key,$projectRoom->geometry?->{$key}) }}" class="block w-full rounded-lg border-slate-300"></label>@endforeach</div>
 <h2 class="font-bold">2. Doors, windows and ventilators</h2><div class="grid md:grid-cols-3 gap-3">
 @foreach(['door'=>'Door','window'=>'Window','ventilator'=>'Ventilator'] as $key=>$label)<div class="rounded-lg bg-slate-50 p-3 space-y-2"><label class="text-sm font-semibold">{{ $label }} count<input type="number" name="{{ $key }}_count" min="0" max="20" required value="{{ old($key.'_count',$defaults[$key.'s'] ?? 0) }}" class="block w-full rounded-lg border-slate-300"></label><label class="text-xs">Width<input type="number" step="0.001" min="0.001" name="{{ $key }}_width" required value="{{ old($key.'_width',$key==='door'?3:($key==='window'?4:2)) }}" class="block w-full rounded-lg border-slate-300"></label><label class="text-xs">Height<input type="number" step="0.001" min="0.001" name="{{ $key }}_height" required value="{{ old($key.'_height',$key==='door'?7:($key==='window'?4:1.5)) }}" class="block w-full rounded-lg border-slate-300"></label></div>@endforeach</div>
 <h2 class="font-bold">3. Optional attached rooms / spaces</h2><p class="text-sm text-slate-600">Use unique names within this flat/floor, such as "Bedroom 1 Attached Washroom". Select the corresponding existing Space Type Master. Each selected space gets its own geometry and four walls.</p>
 @foreach(['washroom'=>'Attached Washroom','balcony'=>'Balcony','wardrobe'=>'Walk-in Wardrobe / Dressing'] as $key=>$label)
 <div class="border rounded-lg p-3 space-y-2"><label class="font-semibold text-sm"><input type="checkbox" name="attached[{{ $key }}][enabled]" value="1" @checked(old('attached.'.$key.'.enabled'))> Create {{ $label }}</label><div class="grid md:grid-cols-5 gap-2"><label class="text-xs">Room name<input name="attached[{{ $key }}][name]" value="{{ old('attached.'.$key.'.name',$projectRoom->name.' '.$label) }}" class="block w-full rounded-lg border-slate-300" maxlength="255"></label><label class="text-xs">Space Type<select name="attached[{{ $key }}][spatial_space_type_id]" class="block w-full rounded-lg border-slate-300"><option value="">Choose type</option>@foreach($spaceTypes as $spaceType)<option value="{{ $spaceType->id }}" @selected(old('attached.'.$key.'.spatial_space_type_id')==$spaceType->id)>{{ $spaceType->name }}</option>@endforeach</select></label>@foreach(['length'=>'Length','width'=>'Width','clear_height'=>'Height'] as $field=>$fieldLabel)<label class="text-xs">{{ $fieldLabel }}<input type="number" step="0.001" min="0.001" name="attached[{{ $key }}][{{ $field }}]" value="{{ old('attached.'.$key.'.'.$field) }}" class="block w-full rounded-lg border-slate-300"></label>@endforeach</div></div>
 @endforeach
 <button class="bg-blue-700 text-white rounded-lg px-6 py-3 font-semibold">Preview room and openings →</button>
 </form>
</div>
@endsection
