@props(['index','designationRoles'=>collect(),'rows'=>[]])
@php
$inputClass='w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100';
$rows=collect($rows)->values();
if($rows->isEmpty()){$rows=collect([['designation_role_id'=>'','quantity'=>'','remarks'=>'']]);}
@endphp
<div class="rounded-lg border border-gray-200 bg-white p-4" data-ref-labour-table data-ref-work-index="{{ $index }}">
<x-rds.section-title title="Labours Used" subtitle="Record manpower deployed specifically for this Work Activity." icon="👷"><x-slot:actions><button type="button" class="rounded-lg bg-green-600 px-3 py-2 text-sm font-semibold text-white hover:bg-green-700" data-ref-add-labour>+ Add Labour</button></x-slot:actions></x-rds.section-title>
<div class="overflow-x-auto"><table class="min-w-[760px] w-full text-sm"><thead class="bg-gray-100 text-xs uppercase tracking-wide text-gray-600"><tr><th class="w-14 px-3 py-3 text-center">#</th><th class="px-3 py-3 text-left">Designation Role</th><th class="w-40 px-3 py-3 text-left">No. of Persons</th><th class="px-3 py-3 text-left">Remarks</th><th class="w-24 px-3 py-3 text-center">Action</th></tr></thead><tbody class="divide-y divide-gray-200" data-ref-labour-body>
@foreach($rows as $labourIndex=>$row)
<tr data-ref-labour-row><td class="px-3 py-3 text-center" data-ref-labour-number>{{ $labourIndex+1 }}</td><td class="px-3 py-3"><select name="works[{{ $index }}][labours][{{ $labourIndex }}][designation_role_id]" class="{{ $inputClass }}" required><option value="">Select Designation</option>@foreach($designationRoles as $role)<option value="{{ $role->id }}" {{ (string)($row['designation_role_id'] ?? '') === (string)$role->id ? 'selected' : '' }}>{{ $role->name }}</option>@endforeach</select></td><td class="px-3 py-3"><input type="number" min="1" step="1" name="works[{{ $index }}][labours][{{ $labourIndex }}][quantity]" value="{{ $row['quantity'] ?? '' }}" class="{{ $inputClass }}" data-ref-labour-quantity required></td><td class="px-3 py-3"><input type="text" maxlength="500" name="works[{{ $index }}][labours][{{ $labourIndex }}][remarks]" value="{{ $row['remarks'] ?? '' }}" class="{{ $inputClass }}"></td><td class="px-3 py-3 text-center"><button type="button" class="rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-700" data-ref-remove-labour>Remove</button></td></tr>
@endforeach
</tbody></table></div>
<template data-ref-labour-template><tr data-ref-labour-row><td class="px-3 py-3 text-center" data-ref-labour-number>__LABOUR_NUMBER__</td><td class="px-3 py-3"><select name="works[{{ $index }}][labours][__LABOUR_INDEX__][designation_role_id]" class="{{ $inputClass }}" required><option value="">Select Designation</option>@foreach($designationRoles as $role)<option value="{{ $role->id }}">{{ $role->name }}</option>@endforeach</select></td><td class="px-3 py-3"><input type="number" min="1" step="1" name="works[{{ $index }}][labours][__LABOUR_INDEX__][quantity]" class="{{ $inputClass }}" data-ref-labour-quantity required></td><td class="px-3 py-3"><input type="text" maxlength="500" name="works[{{ $index }}][labours][__LABOUR_INDEX__][remarks]" class="{{ $inputClass }}"></td><td class="px-3 py-3 text-center"><button type="button" class="rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-700" data-ref-remove-labour>Remove</button></td></tr></template>
</div>
