@props(['index','blocks'=>collect(),'floors'=>collect(),'units'=>collect(),'rooms'=>collect(),'subspaces'=>collect(),'values'=>[]])
@php
$inputClass='w-full rounded-lg border border-gray-300 bg-white px-3 py-3 text-base text-gray-800 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100 sm:py-2 sm:text-sm';
$labelClass='mb-1 block text-sm font-semibold text-gray-700';
@endphp
<div class="rounded-lg border border-gray-200 bg-white p-3 sm:p-4" data-ref-location-selector data-ref-work-index="{{ $index }}">
    <x-rds.section-title title="Work Location" subtitle="Select the exact location where this activity was executed." icon="📍" />
    <div class="grid grid-cols-2 gap-3 md:grid-cols-2 xl:grid-cols-5">
        <div><label class="{{ $labelClass }}">Block</label><select name="works[{{ $index }}][project_block_id]" class="{{ $inputClass }}" data-ref-block-field data-ref-location-block data-selected="{{ $values['project_block_id'] ?? '' }}"><option value="">Select Block</option>@foreach($blocks as $block)<option value="{{ $block->id }}" data-project="{{ $block->project_id }}" {{ (string)($values['project_block_id'] ?? '') === (string)$block->id ? 'selected' : '' }}>{{ $block->name }}</option>@endforeach</select></div>
        <div><label class="{{ $labelClass }}">Floor</label><select name="works[{{ $index }}][project_floor_id]" class="{{ $inputClass }}" data-ref-floor-field data-ref-location-floor data-selected="{{ $values['project_floor_id'] ?? '' }}"><option value="">Select Floor</option>@foreach($floors as $floor)<option value="{{ $floor->id }}" data-project="{{ $floor->project_id }}" data-block="{{ $floor->project_block_id }}" {{ (string)($values['project_floor_id'] ?? '') === (string)$floor->id ? 'selected' : '' }}>{{ $floor->name }}</option>@endforeach</select></div>
        <div><label class="{{ $labelClass }}">Unit / Flat</label><select name="works[{{ $index }}][project_unit_id]" class="{{ $inputClass }}" data-ref-unit-location-field data-ref-location-unit data-selected="{{ $values['project_unit_id'] ?? '' }}"><option value="">Select Unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" data-project="{{ $unit->project_id }}" data-block="{{ $unit->project_block_id }}" data-floor="{{ $unit->project_floor_id }}" {{ (string)($values['project_unit_id'] ?? '') === (string)$unit->id ? 'selected' : '' }}>{{ $unit->name }}</option>@endforeach</select></div>
        <div><label class="{{ $labelClass }}">Room / Space</label><select name="works[{{ $index }}][project_room_id]" class="{{ $inputClass }}" data-ref-room-field data-ref-location-room data-selected="{{ $values['project_room_id'] ?? '' }}"><option value="">Select Room</option>@foreach($rooms as $room)<option value="{{ $room->id }}" data-unit="{{ $room->project_unit_id }}" {{ (string)($values['project_room_id'] ?? '') === (string)$room->id ? 'selected' : '' }}>{{ $room->name }}</option>@endforeach</select></div>
        <div class="col-span-2 xl:col-span-1"><label class="{{ $labelClass }}">Sub-space / Element</label><select name="works[{{ $index }}][project_subspace_id]" class="{{ $inputClass }}" data-ref-subspace-field data-ref-location-subspace data-selected="{{ $values['project_subspace_id'] ?? '' }}"><option value="">Select Sub-space</option>@foreach($subspaces as $subspace)<option value="{{ $subspace->id }}" data-room="{{ $subspace->project_room_id }}" {{ (string)($values['project_subspace_id'] ?? '') === (string)$subspace->id ? 'selected' : '' }}>{{ $subspace->name }}</option>@endforeach</select></div>
    </div>
</div>
