@props(['index','photoTypes'=>[],'rows'=>[]])
@php
$inputClass='w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-800 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100';
$rows=collect($rows)->values();
if($rows->isEmpty()){$rows=collect([['photo_type'=>'Completed Work','caption'=>'']]);}
@endphp
<div class="rounded-lg border border-gray-200 bg-white p-4" data-ref-photo-uploader data-ref-work-index="{{ $index }}">
<x-rds.section-title title="Work Done Photos" subtitle="Upload activity-specific photographic evidence." icon="📷"><x-slot:actions><button type="button" class="rounded-lg bg-green-600 px-3 py-2 text-sm font-semibold text-white hover:bg-green-700" data-ref-add-photo>+ Add Photo</button></x-slot:actions></x-rds.section-title>
<div class="space-y-4" data-ref-photo-body>
@foreach($rows as $photoIndex=>$row)
<div class="rounded-lg border border-gray-200 p-4" data-ref-photo-row><div class="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:items-start"><div class="lg:col-span-3"><label class="mb-1 block text-sm font-semibold text-gray-700">Photo Type</label><select name="works[{{ $index }}][photos][{{ $photoIndex }}][photo_type]" class="{{ $inputClass }}">@foreach($photoTypes as $type)<option value="{{ $type }}" {{ ($row['photo_type'] ?? 'Completed Work') === $type ? 'selected' : '' }}>{{ $type }}</option>@endforeach</select></div><div class="lg:col-span-4"><label class="mb-1 block text-sm font-semibold text-gray-700">Caption</label><input type="text" maxlength="500" name="works[{{ $index }}][photos][{{ $photoIndex }}][caption]" value="{{ $row['caption'] ?? '' }}" class="{{ $inputClass }}"></div><div class="lg:col-span-4"><label class="mb-1 block text-sm font-semibold text-gray-700">Image</label><input type="file" name="works[{{ $index }}][photos][{{ $photoIndex }}][file]" class="{{ $inputClass }}" accept="image/jpeg,image/png,image/webp,image/*" data-ref-photo-file></div><div class="lg:col-span-1 lg:pt-6"><button type="button" class="w-full rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-700" data-ref-remove-photo>Remove</button></div></div><div class="mt-4 hidden rounded-lg border border-gray-200 bg-gray-50 p-3" data-ref-photo-preview-wrap><div class="flex flex-wrap items-start gap-4"><img src="" alt="Photo preview" class="h-28 w-36 rounded-lg border border-gray-200 bg-white object-cover" data-ref-photo-preview><div class="text-sm text-gray-600"><p class="font-semibold text-gray-800">Preview</p><p class="mt-1" data-ref-photo-name></p><p class="mt-1 text-xs text-gray-500" data-ref-photo-size></p></div></div></div></div>
@endforeach
</div>
<template data-ref-photo-template><div class="rounded-lg border border-gray-200 p-4" data-ref-photo-row><div class="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:items-start"><div class="lg:col-span-3"><label class="mb-1 block text-sm font-semibold text-gray-700">Photo Type</label><select name="works[{{ $index }}][photos][__PHOTO_INDEX__][photo_type]" class="{{ $inputClass }}">@foreach($photoTypes as $type)<option value="{{ $type }}">{{ $type }}</option>@endforeach</select></div><div class="lg:col-span-4"><label class="mb-1 block text-sm font-semibold text-gray-700">Caption</label><input type="text" maxlength="500" name="works[{{ $index }}][photos][__PHOTO_INDEX__][caption]" class="{{ $inputClass }}"></div><div class="lg:col-span-4"><label class="mb-1 block text-sm font-semibold text-gray-700">Image</label><input type="file" name="works[{{ $index }}][photos][__PHOTO_INDEX__][file]" class="{{ $inputClass }}" accept="image/jpeg,image/png,image/webp,image/*" data-ref-photo-file></div><div class="lg:col-span-1 lg:pt-6"><button type="button" class="w-full rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-700" data-ref-remove-photo>Remove</button></div></div><div class="mt-4 hidden rounded-lg border border-gray-200 bg-gray-50 p-3" data-ref-photo-preview-wrap><div class="flex flex-wrap items-start gap-4"><img src="" alt="Photo preview" class="h-28 w-36 rounded-lg border border-gray-200 bg-white object-cover" data-ref-photo-preview><div class="text-sm text-gray-600"><p class="font-semibold text-gray-800">Preview</p><p class="mt-1" data-ref-photo-name></p><p class="mt-1 text-xs text-gray-500" data-ref-photo-size></p></div></div></div></div></template>
</div>
